apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka
  namespace: vfde-inv-var-demo-staging
spec:
  podSelector:
    matchLabels:
      app: kafka
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: zookeeper
    ports:
      - port: 9092
        protocol: TCP

  - from:
    - podSelector:
        matchLabels:
          app: api
    ports:
      - port: 9092
        protocol: TCP        

  - from:
    - podSelector:
        matchLabels:
          app: kafka
    ports:
      - port: 9091
        protocol: TCP

  egress:
  - to:
    - podSelector:
        matchLabels:
          app: zookeeper
    ports:
      - port: 2181
        protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: kafka
    ports:
      - port: 9091
        protocol: TCP
