apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ui
  namespace: vfde-inv-var-staging
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: vfde-inv-var
      tier: ui
