apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui
  namespace: vfde-inv-var-demo
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui
  targetCPUUtilizationPercentage: 300
